// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1FLzE_iiOWchPl1gjvYo4TLUiE2VnU5A',
    appId: '1:973892922290:web:e3706f35aa2d3b3cbc92ab',
    messagingSenderId: '973892922290',
    projectId: 'nonghai-6e629',
    authDomain: 'nonghai-6e629.firebaseapp.com',
    storageBucket: 'nonghai-6e629.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSEnAXsi4AHUsi2I88gZSuIzItoiRSQxE',
    appId: '1:973892922290:android:a3f29a8a49ff93cfbc92ab',
    messagingSenderId: '973892922290',
    projectId: 'nonghai-6e629',
    storageBucket: 'nonghai-6e629.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuIWNfdPT9dPo4TdgyRbBOtdrd63KTdqQ',
    appId: '1:973892922290:ios:c2063648f09654c2bc92ab',
    messagingSenderId: '973892922290',
    projectId: 'nonghai-6e629',
    storageBucket: 'nonghai-6e629.appspot.com',
    iosBundleId: 'com.example.nonghai',
  );
}
